#source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0'

target 'LSJHCamera_Example' do
  pod 'LSJHCamera', :path => '../'
#  pod 'LSJHCategory', :path => '/Users/lishihang/Desktop/GitProject/MyWarehouse/LSJHCategory'
  target 'LSJHCamera_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
